### ISSUE TITLE
命名規則を整えよう

### ISSUE THREAD

**Issue by atsushi-ishibashi** [Kohei-Oyama/Client_test_ios#1]
https://github.com/Kohei-Oyama/Client_test_ios/blob/master/Client_test/ViewController.swift#L14

swiftではclass名とかは大文字始まりだけど、インスタンスは小文字スタートかな
で、キャメルケース

**Comment by Kohei-Oyama** [comment]
fixed @bc974532439956404723135b30cdd6cab1c8dda8 to @34998d25a13c7ccf26f0d6f41e311a5cab43f227
